- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-yoga-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - docker-build-monasca-service
    post:
      jobs:
        - publish-monasca-client-docker-image
    periodic:
      jobs:
        - publish-monasca-client-docker-image
    release:
      jobs:
        - publish-monasca-client-docker-image

- job:
    name: publish-monasca-client-docker-image
    parent: build-monasca-docker-image
    post-run: playbooks/docker-publish.yml
    required-projects:
      - openstack/monasca-common
    vars:
      publisher: true
    secrets:
      - doker_hub_login_client

- secret:
    name: doker_hub_login_client
    data:
      user: !encrypted/pkcs1-oaep
        - QdHgQ9lGfeOypCKTX9funuwbHCVRhUGfyswosl9whSskzy1EhztLSPpP5PPHg/ZM0Ag8o
          VAHT6La7oroTDeWYcDJmN8Zc5mslQlcskwoq9TN/VWEhY36+OF3k938Zr78URwOT5Hqm4
          ch+itjmydrQOrqcCwJ3ROrrJ2XpIMainz567U1HYuUari9B3zOUTW3xJfqbJ8UJIn/Irj
          qEHn4Rn/RT3fOBcLwZfWJOcuwes8dsQykXNufLxXy2UGpdcHlE6lAAnRBgN/EPBxtqpAB
          j+TO3s3yJLCIXDPIV+nST8z6EbvYc+woM4O1PN0AQ/tfyulFGvDTJNIdKenUBD99rBBJS
          RCBZ0hhVgqDE4y4fcHh6STde0UHUQgwdX9lbdC2MGZah0bjUWG67QMwdtiiBwktbz3nza
          a7yjd6/6di3zstDDGRLvZ5+vJ0cE/4eeWUmXcq2c0dtggaFDXYhOIoM1xfHKNvMN6QjM1
          kETvG2aw/PyNYIJkNic19Qk7UbOrgKduZUA6K17xQ5lqIJn/JfRVQyvoi0pLMCsa1NSe+
          wlpg9acJ46l0licRJ8o+QA02cFcrl9gBY5x0WwO3N/+LOxc40L+hHJi2vzduQO0ikCYa4
          Lerew8vrpf2EZ3JV5JEuIQ0/q5V5ZXhCeJQ6JBdLusYF3LzHRkX+7DCt3UMgaU=
      password: !encrypted/pkcs1-oaep
        - uZOFnKJzCV26Ea3KtPmK0WaTCV6YqLgS0Y5BolGq4MahKftVXxDbWRtVMQWnwx8mMugmh
          A8mtchoyvrIvH5gjU7SmvVYAyH5KJGdKnb/9jbYTJ/Zq9f2CFd10hlomIUIlbDixAIMmV
          rbcexomEY5b15lF9F4I3ovwPEsqu0YcGMW7ABPdZaZx5JGDgYXXGWpy3CFvVV/MIzLbV+
          wgByN7RsBNEFY44/xLTBkjN4RHOWTo1hFLeblI2pRJ40fzPw6fuUpeG1oPV/l4h9cjTgq
          KMr4RuxxvCI3D0nWmq8SrIJ446erEldolJtpKRLqn1GTcGgyQbUgiXA0Nd44sFAcmwTBz
          vK4rgD9Akhz/bsV6P8P5x25YoU6oS8Vws4mKu+iw3TWn0e+467oFvw+PD4e3+JbSSofyh
          6gVRsXK+Ls7YMNdnoAe8XXh76IBfC639olAgFU7ewtcsOLAiVrqIIynWmprBJZ2apEBxs
          jRNQpBgkTtUaaBcb3uGY3Fcip7PDcjcApYoaLHAUi2P2+o5gatsmySLb64g4O3rddn7Wf
          8uSWv123X4zvXIk3V7FmCeSXgamVuZKpRHbFIeq9S+13ze1HBce6s36egoiGTfCMq5wLr
          XwRwytGr8JoI4c8YIQXffYxJhhbgA9Qn+FalsrJIQNR03GnA2oUKKNsZExwcPs=
